# Generated by Django 4.2.3 on 2024-01-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_membership_stripe_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='name',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='stripe_payment_id',
        ),
        migrations.AddField(
            model_name='membership',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='membership',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='membership',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
