# Generated by Django 4.2.3 on 2024-01-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_membership_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='selected_plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
